[phases.setup]
nixPkgs = ['nodejs_18', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
    'npm ci --only=production',
    'python3 -m venv venv',
    'source venv/bin/activate && pip install yfinance pandas numpy requests multitasking platformdirs pytz frozendict peewee beautifulsoup4 curl_cffi protobuf websockets'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'npm start'